<div class="container">
	<div class="jumbotron">
		<h2></h2>
<p>Peaaegu igas kodus leidub vanu fotoalbumeid või karpe fotodega. Vanu fotosid sirvides meenuvad vanematele inimestele tihti ka mälestuskillud varasema aja inimestest ja oludest. Need teadmised kaovad kiiresti koos vanema põlvkonnaga. Ometi on see väärtuslik osa meie ühisest kultuuripärandist, mida ei tohiks lasta kaotsi minna. Praegu on veel võimalik vältida olukorda, kus meie käsutuses on mahukad vanad pildikogud, mille sisu kohta keegi midagi ei tea. Portaal „Vanad albumid“ on loodud selleks, et pakkuda inimestele võimalust fotokogude jagamiseks, täiendavate andmete ja lugude kogumiseks; ühtlasi kanname hoolt selle eest, et fotod ja kogu taustateave säiliks turvaliselt Eesti Kirjandusmuuseumi digitaalarhiivis. „Vanad albumid“ on mõeldud avalikuks kasutuseks kogu rahvale – pärand ja pärimused säilivad üle aegade eelkõige siis, kui nende vastu on huvi, ning neid antakse edasi, kasutatakse ja jagatakse.</p>
<p>Kontakt. Murede ja küsimuste korral palun kirjutage aadressil mari@folklore.ee</p>

<h2>Albumid</h2>

<p>Keskseks üksuseks siinses portaalis on albumid. See ei tähenda, et lisatavad pildid peaksid tingimata kuuluma ühte füüsilisse albumisse. Albumi all mõtleme eelkõige terviklikku kogu - kas siis tõesti reaalset albumit - või fotosid millel on mingi sisuline ühisosa (ühe isiku elu jooksul kogunenud pildid, pildid ühest sündmusest, ühest külast, ühe asutuse või kooli mingi ajastu pildid vm.). Loomulikult võib üles laadida ka ühest pildist koosneva albumi. Kui laete üles kellelegi teisele kuuluva albumi pilte, siis küsige enne kindlasti, kas piltide omanik sellega nõus on. Enne piltide üles laadimist tuleks sisestada andmed albumi kohta, milline on albumi tekke- ja ajalugu, kas see on seotud mingi kindla piirkonna või ajajärguga ning kellele originaalfotod kuuluvad. Lisaks sellele on võimalik lisada albumile tunnuseid, mis võimaldavad hiljem albumite hulgas otsinguid teha ning kanduvad edasi ka albumisse kuuluvatele piltidele (iga pildi juures saab neid andmeid muuta): linn/kihelkond/välismaa, fotograaf, aeg - lisage need andmed üksnes siis, kui see määratlus kehtib enamikule fotodest (näiteks kuupäev kui tegu on ühel konkreetsel päeval tehtud fotodega). Märksõnana pange kirja olulised albumit iseloomustavad tunnused (näiteks küla nimi, sündmus, asutus) võimalikult arusaadavalt, korrektselt ja kompaktselt. Võimalusel kasutage juba kasutusel olevaid märksõnu</p>

<h2>Pildid</h2>

<p>Pildid saab veebikeskkonda üles laadida ainult digitaalkujul. Mida kvaliteetsemad fotod üles laete, seda laiemad on selle kasutusvõimalused tulevikus. Samas võtaks plakatikvaliteedis skaneeritud fotode üleslaadimine (sõltuvalt internetiühenduse kiirusest) tohutu aja. Seepärast ei saa me siinkohal ka täpsemaid soovitusi anda, igaüks peab lähtuma siin oma soovidest, võimalustest ja ressurssidest. Võimalusel kasutage TIFF vormingut, kuid lubatud on ka muudes vormingutes pildid. Juhul, kui soovite säilitamiseks anda ka originaalid või tõesti suuremahulised fotod, siis palun võtke ühendust e-posti teel ning leiame lahenduse, kuidas seda teha. Albumitesse on tihti kogunenud lisaks fotodele ka muud materjali, postkaarte, laululehti, salmikesi. Ka need moodustavad osa tervikust ning on soovitav üles laadida albumisse kuuluvana.
Fotode üles laadimisel pidage palun võimaluse piires silmas piltidel olevate isikute huvisid. Portaal on keskendunud eelkõige vanadele fotodele, mille üleslaadimise vastu enamasti inimestel midagi ei ole. Iseenesest ei ole ka midagi hullu, kui fotodel on praegu veel elavaid inimesi, otse vastupidi! Kuid need inimesed - juhul kui nad ei soovi enda pildi avalikku väljanäitamist - võivad sellest teada anda kas albumi omanikule või fotoportaali haldajale, kes märgib selle pildi mitteavalikuks. Sama võib teha piltide üleslaadija juba algsel üles laadimisel. Palun ärge lisage avalikku kasutusse kompromiteerivaid fotosid.
Iga foto juures saab üleslaadija kirjeldada foto sisu, andmeid, leida kaardilt (või kirjutada sõnadega) pildistamise koht ning tuvastada fotol olevad inimesed. Teised kasutajad saavad samuti tuvastada fotol olevaid inimesi ning lisada kommentaare foto sisu või andmete kohta.
</p>

	  	<h2>Inimesed</h2>
	  	<p>Eraldi koondame teavet fotodega seotud isikute kohta. Lähtealusena kasutame Kirjandusmuuseumi kogujate ja annetajate registri kandeid. Iga inimese kohta on võimalik lisada lisaks nimele ka tema elukohad (linna/kihelkonna täpsusega) ning sünniaeg. See info peaks võimaldama tuvastada suhteliselt ühemõtteliselt tuvastada fotodega seotud inimesed. Täiendavad teadmised inimese elu ja tegevuse kohta, võimalikud alternatiivsed nimekujud, täpsemad elukohad, ameti, surmaaja, ka mälestused ja lood võib lisada kommentaarina. Neid andmeid kirjutades palun jälgige, et teie kirjapanekud ei riivaks otseselt kedagi. Vajadusel on ka kirja pandud eluloolised andmed võimalik muuta mitteavalikuks.</p>

	    	<h2>Kogukonnad</h2>
	    	<p>Inimestele pakuvad enamasti huvi nendega kuidagi seotud kogukondade fotod. Fotosid ja albumeid on võimalik vaadelda kas linna/kihelkonna järgi või märksõna järgi. Kui olete huvitatud näiteks ühe küla piltidest, siis lisage küla nimi märksõnana; kui ühe asutuse kollektiivi piltidest, siis lisage selle asutuse nimi; kui külakapelli piltidest, siis lisage selle nimetus. Märksõnad, eriti albumite märksõnad, toimivad siinses süsteemis kui kogukonnasildid.</p>

  	    	<h2>Viitamine</h2>
  	    	<p>Siinseid fotosid võib kopeerida ja ka avalikult kasutada üksnes tingimusel, et viidatakse nii siinsele fotoportaalile kui piltide omanikule ning lisatakse vastava pildi ja albumi netiaadress. Näiteks: Karukõrva mägi Kalju külas. – Vanad albumid. EKM fotoportaal. Foto Peeter Paani fotokogust, www.kirmus.ee/vanadfotod/album1pilt2.jpg. Üles laetud pildid saavad hiljem kõik ka arhiiviviite, mis on leitav EKM digitaalarhiivist Kivike, http://kivike.kirmus.ee, ning viitamisel võib kasutada ka seda.</p>
  	      </div>
</div>


